import { Inter } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import Navbar from "@/components/users/shared/NavbarUsers";
import Footer from "@/components/users/shared/FooterUsers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BlushBelle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
