import { Inter } from "next/font/google";
import "./globals.css";
import EgoisticNavbar from "@/components/utils/EgosticNavbar";
import EgoisticFooter from "@/components/utils/EgosticFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EgoisticNavbar/>
        {children}
        <EgoisticFooter/>
        </body>
    </html>
  );
}
